"""add received_by to payments

Revision ID: 9db7c07b475d
Revises: c5e3126ab6a6
Create Date: 2026-07-17 11:15:00.532223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db7c07b475d'
down_revision: Union[str, Sequence[str], None] = 'c5e3126ab6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('received_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'received_by')
    # ### end Alembic commands ###
