"""add resolution fields to housekeeping

Revision ID: c5e3126ab6a6
Revises: 81aede6b9a8c
Create Date: 2026-07-17 10:04:20.801500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e3126ab6a6'
down_revision: Union[str, Sequence[str], None] = '81aede6b9a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housekeeping', sa.Column('resolved_by', sa.String(length=100), nullable=True))
    op.add_column('housekeeping', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('housekeeping', sa.Column('resolution_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housekeeping', 'resolution_notes')
    op.drop_column('housekeeping', 'resolved_at')
    op.drop_column('housekeeping', 'resolved_by')
    # ### end Alembic commands ###
